import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { BsMagic, BsClipboard, BsCheck, BsTrash, BsClockHistory, BsExclamationCircle } from 'react-icons/bs';

const AIToolDemo = () => {
  const [prompt, setPrompt] = useState('');
  const [output, setOutput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [history, setHistory] = useState([]);
  const [timestamp, setTimestamp] = useState('');

  // Load history from localStorage on mount
  useEffect(() => {
    const savedHistory = localStorage.getItem('smartai_history');
    if (savedHistory) {
      try {
        setHistory(JSON.parse(savedHistory));
      } catch (e) {
        console.error('Failed to parse history', e);
      }
    }
  }, []);

  const generateMockResponse = (userPrompt) => {
    const responses = [
      `Here is a professional AI-generated response for your prompt: "${userPrompt}"\n\nThis text is simulated to demonstrate how SmartAI would instantly return beautifully formatted, context-aware content. In a real application, this would be connected to an advanced LLM endpoint.\n\nKey points:\n- Fast generation\n- Contextual understanding\n- Ready to use`,
      `Based on your request, this is the optimized content generated by SmartAI.\n\nPrompt: "${userPrompt}"\n\nWe've ensured the tone is engaging and professional. Feel free to copy this and use it directly in your workflow.`
    ];
    return responses[Math.floor(Math.random() * responses.length)];
  };

  const saveToHistory = (newPrompt, newResponse, time) => {
    const newItem = { prompt: newPrompt, response: newResponse, timestamp: time };
    const updatedHistory = [newItem, ...history].slice(0, 5); // Keep last 5 prompts
    setHistory(updatedHistory);
    localStorage.setItem('smartai_history', JSON.stringify(updatedHistory));
  };

  const handleGenerate = (e) => {
    e.preventDefault();
    setError('');

    if (prompt.trim().length < 5) {
      setError('Prompt must be at least 5 characters long.');
      return;
    }

    setIsGenerating(true);
    
    // Simulate API call delay (2-3 seconds)
    const delay = Math.floor(Math.random() * 1000) + 2000;
    
    setTimeout(() => {
      const mockResponse = generateMockResponse(prompt);
      const now = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      
      setOutput(mockResponse);
      setTimestamp(now);
      saveToHistory(prompt, mockResponse, now);
      setIsGenerating(false);
    }, delay);
  };

  const copyToClipboard = async () => {
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      setError('Failed to copy to clipboard.');
      setTimeout(() => setError(''), 3000);
    }
  };

  const clearCurrent = () => {
    setPrompt('');
    setOutput('');
    setError('');
    setTimestamp('');
  };

  const clearHistory = () => {
    setHistory([]);
    localStorage.removeItem('smartai_history');
  };

  const loadHistoryItem = (item) => {
    setPrompt(item.prompt);
    setOutput(item.response);
    setTimestamp(item.timestamp);
    setError('');
  };

  const wordCount = output ? output.trim().split(/\s+/).filter(word => word.length > 0).length : 0;

  return (
    <section className="py-24 relative" id="demo">
      {/* Background glow */}
      <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[600px] h-[600px] bg-purple-600/10 blur-[100px] rounded-full pointer-events-none" />

      <div className="container mx-auto px-6 max-w-5xl relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold mb-6">
            Experience the <span className="text-gradient">Magic</span>
          </h2>
          <p className="text-slate-400 text-lg max-w-2xl mx-auto">
            Try our text generator right now. Enter a prompt below and see how SmartAI transforms your ideas into polished content instantly.
          </p>
        </div>

        <div className="flex flex-col gap-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="glass-card rounded-3xl p-6 md:p-8 relative overflow-hidden"
          >
            {/* Decorative border gradient */}
            <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 to-purple-500/10 pointer-events-none" />

            <div className="grid md:grid-cols-2 gap-8 relative z-10">
              {/* Input Section */}
              <div className="flex flex-col h-full">
                <label className="text-sm font-medium text-slate-300 mb-3 flex items-center gap-2">
                  <BsMagic className="text-blue-400" /> Your Prompt
                </label>
                <form onSubmit={handleGenerate} className="flex flex-col flex-grow relative">
                  <div className="relative flex-grow flex flex-col mb-4">
                    <textarea
                      value={prompt}
                      onChange={(e) => {
                        setPrompt(e.target.value);
                        if (error) setError('');
                      }}
                      placeholder="Enter your prompt here..."
                      className={`glass-input p-4 w-full flex-grow resize-none min-h-[200px] pb-8 ${error ? 'border-rose-500/50 focus:border-rose-500/50 focus:ring-rose-500/50' : ''}`}
                    />
                    <div className="absolute bottom-3 right-4 text-xs text-slate-500">
                      {prompt.length} chars
                    </div>
                  </div>
                  
                  <AnimatePresence>
                    {error && (
                      <motion.div
                        initial={{ opacity: 0, y: -10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -10 }}
                        className="flex items-center gap-2 text-rose-400 text-sm mb-4 bg-rose-500/10 p-3 rounded-lg border border-rose-500/20"
                      >
                        <BsExclamationCircle /> {error}
                      </motion.div>
                    )}
                  </AnimatePresence>

                  <div className="flex gap-3">
                    <button
                      type="button"
                      onClick={clearCurrent}
                      disabled={isGenerating || (!prompt && !output)}
                      className="btn-secondary px-4 py-3 shrink-0 disabled:opacity-50 disabled:cursor-not-allowed"
                      title="Clear"
                    >
                      <BsTrash />
                    </button>
                    <button
                      type="submit"
                      disabled={isGenerating || !prompt.trim()}
                      className={`btn-primary w-full flex items-center justify-center gap-2 ${
                        isGenerating || !prompt.trim() ? 'opacity-70 cursor-not-allowed' : ''
                      }`}
                    >
                      {isGenerating ? (
                        <span className="flex items-center gap-2">
                          <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" /> Generating...
                        </span>
                      ) : (
                        <>Generate Content <BsMagic /></>
                      )}
                    </button>
                  </div>
                </form>
              </div>

              {/* Output Section */}
              <div className="flex flex-col h-full">
                <div className="flex items-center justify-between mb-3">
                  <label className="text-sm font-medium text-slate-300">AI Output</label>
                  <div className="flex items-center gap-4">
                    <AnimatePresence>
                      {copied && (
                        <motion.span
                          initial={{ opacity: 0, x: 10 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0 }}
                          className="text-xs text-emerald-400 flex items-center gap-1"
                        >
                          <BsCheck size={14} /> Copied to clipboard!
                        </motion.span>
                      )}
                    </AnimatePresence>
                    <button
                      onClick={copyToClipboard}
                      disabled={!output}
                      className="text-slate-400 hover:text-white transition-colors disabled:opacity-50 flex items-center gap-1 text-sm"
                      title="Copy to clipboard"
                    >
                      <BsClipboard size={16} /> Copy
                    </button>
                  </div>
                </div>
                
                <div className="relative flex-grow flex flex-col">
                  <AnimatePresence mode="wait">
                    {output ? (
                      <motion.div
                        key="output"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="glass-input p-4 w-full flex-grow min-h-[200px] overflow-y-auto font-mono text-sm leading-relaxed whitespace-pre-wrap text-slate-200"
                      >
                        {output}
                      </motion.div>
                    ) : (
                      <motion.div
                        key="placeholder"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="glass-input p-4 w-full flex-grow min-h-[200px] flex items-center justify-center text-slate-600 italic text-sm"
                      >
                        Generated output will appear here...
                      </motion.div>
                    )}
                  </AnimatePresence>

                  {/* Output Footer */}
                  {output && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="absolute bottom-0 left-0 right-0 p-3 bg-black/60 backdrop-blur-md border-t border-white/10 rounded-b-xl flex justify-between items-center text-xs text-slate-400"
                    >
                      <span>{wordCount} words</span>
                      <span>{timestamp && `Generated at ${timestamp}`}</span>
                    </motion.div>
                  )}
                </div>
              </div>
            </div>
          </motion.div>

          {/* History Section */}
          {history.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="glass-card rounded-2xl p-6 relative overflow-hidden"
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300 flex items-center gap-2">
                  <BsClockHistory className="text-purple-400" /> Prompt History
                </h3>
                <button
                  onClick={clearHistory}
                  className="text-xs text-slate-500 hover:text-rose-400 transition-colors flex items-center gap-1"
                >
                  <BsTrash /> Clear History
                </button>
              </div>
              
              <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
                <AnimatePresence>
                  {history.map((item, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.95 }}
                      transition={{ delay: index * 0.05 }}
                      onClick={() => loadHistoryItem(item)}
                      className="bg-white/5 border border-white/10 rounded-xl p-4 cursor-pointer hover:bg-white/10 hover:border-purple-500/30 transition-all group"
                    >
                      <div className="flex justify-between items-start mb-2">
                        <span className="text-xs text-purple-400 font-medium truncate pr-4">{item.timestamp}</span>
                        <BsMagic className="text-slate-500 group-hover:text-purple-400 transition-colors shrink-0" size={12} />
                      </div>
                      <p className="text-sm text-slate-300 line-clamp-2 text-ellipsis leading-relaxed">
                        "{item.prompt}"
                      </p>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </div>
      </div>
    </section>
  );
};

export default AIToolDemo;
